---
  spark_executor_memory:
      min: 1024
      max: 4028
      default: 1024
  spark_driver_memory:
        min: 1024
        max: 4028
        default: 1024
  spark_shuffle_service_index_cache_entries:
        min: 512
        max: 2048
        default: 1024
  spark_shuffle_sort_bypassMergeThreshold:
        min: 100
        max: 1000
        default: 200
  spark_shuffle_accurateBlockThreshold:
      min: 10485760
      max: 1048576000
      default: 104857600
  spark_broadcast_blockSize:
      min: 2
      max: 128
      default: 4
  spark_executor_cores:
      min: 1
      max: 6
      default: 3
  spark_speculation_interval:
      min: 10
      max: 1000
      default: 100
  spark_kryoserializer_buffer_max:
      min: 8
      max: 128
      default: 64
  spark_kryoserializer_buffer:
      min: 2
      max: 128
      default: 64







    
    

    


    









    







    
    
    
    
