- hosts: master,worker1,worker2
  gather_facts: false
  vars:
    ansible_sudo_pass: 123
    db_name: spark
    spark_home: "/home/zhangl/sd_spark/{{db_name}}/{{task_name}}"
    spark_logs: "{{spark_home}}/spark/logs"
    spark_work: "{{spark_home}}/spark/work"
  remote_user: zhangl

  tasks:
    - name: clear spark_logs
      file:
        path: "{{spark_logs}}"
        state: "{{item}}"
      with_items:
        - absent
        - directory
    - name: clear spark_work
      file:
        path: "{{spark_work}}"
        state: "{{item}}"
      with_items:
        - absent
        - directory